### ISSUE TITLE
http://store-api:9091/ not available

### ISSUE THREAD

**Issue by mraible** [embesozzi/keycloak-openfga-workshop#5]
Hello @embesozzi!

I tried to do this workshop today and I'm unable to access `http://store-api:9091/` after running this command:

```
docker-compose -f docker-compose.yml -f docker-compose-apps.yml -f docker-compose-openfga.yml up
```

Here is what I see in Docker:

<img width="1382" alt="Screenshot 2023-11-01 at 1 29 58 PM" src="https://github.com/embesozzi/keycloak-openfga-workshop/assets/17892/b9d4b212-c889-4445-abb9-9ace1f1e9de1">

My `/etc/hosts` file has:

```
127.0.0.1	localhost
127.0.0.1	keycloak
127.0.0.1	openfga store store-api
```

**Comment by embesozzi** [comment]
Hi Matt,
Thanks for the feedback. I have resolved the issue by adjusting the port mapping in [docker-compose-apps.yml#L26](https://github.com/embesozzi/keycloak-openfga-workshop/blob/main/docker-compose-apps.yml#L26).
I have also made some other minor [changes](https://github.com/embesozzi/keycloak-openfga-workshop/releases/tag/2.1.1). Could you please pull the latest updates? And then proceed with rebuilding the workshop.

Please let me know if everything is working correctly.

**Comment by mraible** [comment]
@embesozzi I can confirm that your changes have solved this issue. I'll continue from [Post configuration steps](https://github.com/embesozzi/keycloak-openfga-workshop#post-configuration-steps) tomorrow. I'm closing this issue since it's resolved.
